[package]
name = "FitnessCoin"
version = "1.0.0"
authors = ["fitness-dapp"]

[addresses]
fitness_coin = "_"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]